# Generated by Django 2.0 on 2019-06-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messege',
            new_name='Message',
        ),
    ]
