# Generated by Django 2.0 on 2019-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20190605_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pubtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
