# Generated by Django 2.0 on 2019-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20190606_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
