# Generated by Django 2.0 on 2019-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.TextField(max_length=6),
        ),
    ]
