# Generated by Django 2.0 on 2019-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20190607_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AlterField(
            model_name='message',
            name='leavemessage',
            field=models.TextField(max_length=1000),
        ),
    ]
