# Generated by Django 2.0 on 2019-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_auto_20190608_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pubtime',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
