# Generated by Django 2.0 on 2019-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20190608_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pubtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
