# Generated by Django 2.0 on 2019-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_auto_20190609_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
