# Generated by Django 2.0 on 2019-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_visitor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=1, upload_to='newapp/image/'),
            preserve_default=False,
        ),
    ]
