# Generated by Django 2.0 on 2019-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_auto_20190619_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='newapp/static/newapp/userupload/'),
        ),
    ]
