# Generated by Django 2.0 on 2019-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_auto_20190624_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='newapp/static/newapp/userupload/'),
        ),
    ]
