# Generated by Django 2.0 on 2019-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_auto_20190624_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(max_length=255, upload_to='newapp/static/newapp/userupload/'),
        ),
    ]
